apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 1m
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nats
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: nats
  interval: 1m
  prune: true
  validation: client
  targetNamespace: project
