apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-prometheus
  namespace: prometheus
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '21.0.3'
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 1m
