apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: secrets
  url: https://github.com/tsa-dom/devops-with-kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m
  path: ./Project/manifests/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
