apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: project-repo
  interval: 1m
  path: ./Project
  prune: true
  validation: client
  targetNamespace: project
