apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: psql-sa-key
  namespace: project
spec:
  interval: 1m
  path: "./"
  sourceRef:
    kind: GitRepository
    name: psql-sa-key
  decryption:
    provider: sops
    secretRef:
      name: sops-age
